/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesIndexRouteImport } from './routes/files.index'
import { Route as FilesIdRouteImport } from './routes/files.$id'
import { Route as SchemasIndexRouteImport } from './routes/schemas.index'
import { Route as SchemasIdRouteImport } from './routes/schemas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIdRoute = FilesIdRouteImport.update({
  id: '/files/$id',
  path: '/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasIndexRoute = SchemasIndexRouteImport.update({
  id: '/schemas/',
  path: '/schemas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasIdRoute = SchemasIdRouteImport.update({
  id: '/schemas/$id',
  path: '/schemas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files/$id': typeof FilesIdRoute
  '/schemas/$id': typeof SchemasIdRoute
  '/files/': typeof FilesIndexRoute
  '/schemas/': typeof SchemasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files/$id': typeof FilesIdRoute
  '/schemas/$id': typeof SchemasIdRoute
  '/files': typeof FilesIndexRoute
  '/schemas': typeof SchemasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files/$id': typeof FilesIdRoute
  '/schemas/$id': typeof SchemasIdRoute
  '/files/': typeof FilesIndexRoute
  '/schemas/': typeof SchemasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/files/$id' | '/schemas/$id' | '/files/' | '/schemas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/files/$id' | '/schemas/$id' | '/files' | '/schemas'
  id: '__root__' | '/' | '/files/$id' | '/schemas/$id' | '/files/' | '/schemas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesIdRoute: typeof FilesIdRoute
  SchemasIdRoute: typeof SchemasIdRoute
  FilesIndexRoute: typeof FilesIndexRoute
  SchemasIndexRoute: typeof SchemasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$id': {
      id: '/files/$id'
      path: '/files/$id'
      fullPath: '/files/$id'
      preLoaderRoute: typeof FilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/': {
      id: '/schemas/'
      path: '/schemas'
      fullPath: '/schemas/'
      preLoaderRoute: typeof SchemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/$id': {
      id: '/schemas/$id'
      path: '/schemas/$id'
      fullPath: '/schemas/$id'
      preLoaderRoute: typeof SchemasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesIdRoute: FilesIdRoute,
  SchemasIdRoute: SchemasIdRoute,
  FilesIndexRoute: FilesIndexRoute,
  SchemasIndexRoute: SchemasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
