/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'

const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/datasets': typeof DatasetsRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/datasets': typeof DatasetsRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/datasets': typeof DatasetsRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/builder' | '/datasets' | '/viewer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builder' | '/datasets' | '/viewer'
  id: '__root__' | '/' | '/builder' | '/datasets' | '/viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  DatasetsRoute: typeof DatasetsRoute
  ViewerRoute: typeof ViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  DatasetsRoute: DatasetsRoute,
  ViewerRoute: ViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
